
info:
  version: 0.0.2
  title: "shifttree API"

openapi: 3.0.3

paths:
  # Login Endpoint. Body contains email and password json file. 
  # Response contains a User(username, jwt)
  /login:
    post:
      description: Login
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        200:
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'
  /register:
    post:
      description: Registration
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationCredentials'
      responses:
        201:
          description: Successful Registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Registration Sucessful"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'
  /schedules:
    post:
      description: Create a new schedule
      security:
        - Bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                owner:
                  type: string
                  nullable: true
                name:
                  type: string
                description:
                  type: string
                  nullable: true
      responses:
        201:
          description: Created successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - scheduleId
                properties:
                  scheduleId:
                    type: string
                    format: uuid
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'
  /shiftTreeID:
    get:
      security:
        - Bearer: []
      description: Gets the ID Code for a shiftTree, if the user making request is Owner
      responses: 
        401:
          description: Unauthorised
        404: 
          description: Not found
        200: 
          description: ID Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UUID'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'
      parameters:
        - name: ShiftTree
          in: query
          schema:
            type: string
          description: The ShiftTree to generate code for
          required: true
  /join:
    put:
      security:
        - Bearer: []
      description: Adds a user to the queue for shiftTree membership
      responses:
        404:
          description: UUID does not have corresponding ShiftTree
        200:
          description: Request To Join Successful
        500:
          description: Unable to add User to Schedule
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'
      parameters:
        - name: ShiftTreeID
          in: query
          schema:
            $ref: '#/components/schemas/UUID'
  /hello:
    get:
      summary: "Test endpoint"
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
          description: "Name to greet"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    example: "Hello World"
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
  schemas:
     UnexpectedError:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
     Credentials:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
     RegistrationCredentials:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - username
        - email
        - password
     User:
      type: object
      properties:
        name:
          type: string
        accessToken:
          type: string
      required:
        - name
        - accessToken
     UserInfoPreview:
      type: object
      required:
        - id
        - displayName
        - email
      properties:
        id:
          type: string
          format: uuid
        displayName:
          type: string
        email:
          type: string
        profileImageUrl:
          type: string
     UUID:
      type: string
      pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'